### PR TITLE
Update system requirements for 8.8

### PR DESCRIPTION
**Pull request by jorgedlcruz**
Couple of updates for ZCS 8.7 and 8.8

### CODE REVIEW

**Review by fatkudu — APPROVED** [review]

**Review by grishick — APPROVED** [review]

**Comment by gordyt** [comment]
@jorgedlcruz  this PR should be rebased onto the `develop` branch and issued against `develop`.  If you like I'll be happy to do that for you.

**Comment by jorgedlcruz** [comment]
Hi, Gordon if you can do it that would be great, these changes are for 8.7 and 8.8.

**Comment by gordyt** [comment]
OK if they really apply to 8.7 as well, I'll go ahead and merge it into master and move the (8.7.6) tag up to include the change.

**Comment by gordyt** [comment]
This shows as closed but has been merged.

**Pull request closed without merging**
