### PR TITLE
Memcached updates

### PR DESCRIPTION
**Pull request by tmclane**
Make the fact that zimbra-memcached is a requirement of zimbra-proxy a bit more evident.

### CODE REVIEW

**Comment by tmclane** [comment]
If 'master' is the wrong branch to target let me know and I will update the PR.

**Review by fatkudu — APPROVED** [review]

**Comment by fatkudu** [comment]
Is it worth revisiting this now?  I imagine should be re-targeted at develop.

**Comment by tmclane** [comment]
You got it.

**Comment by tmclane** [comment]
FYI: Created the 'develop' branch and retargeted this PR against it.

**Review by fatkudu — APPROVED** [review]

**Review by gordyt — APPROVED** [review]

**Review by grishick — APPROVED** [review]

**Pull request closed without merging**
