### PR TITLE
Cleanup in preparation for translations.

### PR DESCRIPTION
**Pull request by jeastman**
Ordered lists have been indented per recommendation from po4a.
Indentation cleanup of existing lists.

### CODE REVIEW

**Comment by jeastman** [comment]
I meant to issue this against develop, not master. Cannot figure out how to change that from within the github interface.

**Comment by gordyt** [comment]
I think you have to close the PR and redo it.

**Comment by gordyt** [comment]
Changes look fine though!

**Comment by jeastman** [comment]
Closing in favor of pull-request on develop

**Pull request closed without merging**
