### PR TITLE
Modified wrong translation for 2FA

### PR DESCRIPTION
**Pull request by mamishoho**
Modified wrong translation for 2FA and an old link.

### CODE REVIEW

**Review by fatkudu — APPROVED** [review]

**Comment by mamishoho** [comment]
@fatkudu @gordyt Could you please merge these into the Upstream? Or would you mind if I ask you to give me a permission to do so as 403 error returns.
Best,
Mami

**Comment by gordyt** [comment]
Hey @mamishoho ,
I've been on PTO. If it is OK, I will take care of this tomorrow when I am back in the office.

**Comment by mamishoho** [comment]
@gordyt  Anytime (even next month) is fine by me! Thank you for taking case of these!

**Comment by fatkudu** [comment]
@mamishoho I will leave this for Gordon  I'm on vacation until the new year and will probably be only limited availabilty for recuperation reasons.

**Comment by gordyt** [comment]
This pull request has been merged and closed.

**Pull request merged**
